### ISSUE TITLE
Could you please make a new release?

### ISSUE THREAD

**Issue by palxex** [dborth/sdl-wii#53]
Recent DevKitPPC seems upgrades ABI. Use last SDL-Wii released 2013 will complain `undefined reference to `__ctype_ptr__'`, and after recompilation the warning eliminated.

**Comment by iyenal** [comment]
Have the same problem, the library needs a release update.
By the way do you have a compilated version of the current SDL @palxex please ?

**Comment by palxex** [comment]
@iyenal Now I'm using old version of devkitPro and old version of SDL-wii combination. With latest devkitPro, even after the recompilation, there're much more runtime problem, which I've tired to fix one by one, while none of them exist in previous releases. 
Please see my [travis.yml](../../../sdlpal/sdlpal/blob/master/.travis.yml), under `TARGET=wii` section.

**Comment by iyenal** [comment]
Thanks very much @palxex, I will directly use the toolchain versions you reported on your compilation config. file. For further reference to people that may have this issue also, use these versions :
- devkitPPC r27
- libogc 1.8.12
- libfat-ogc 1.0.13
- and the last Wii SDL, SDL.Wii 10-28-2013
courtesy of palxex, thanks again.

**Comment by palxex** [comment]
@iyenal Glad it helped.

**Comment by Oibaf66** [comment]
DevkitPPC r29 requires a new version of portlibs which has never been released.
https://devkitpro.org/viewtopic.php?f=13&t=8643
TODO 
•recompile portlibs with latest tools.
•[strike]merge and tag libraries in git repos.[/strike]
The latest working devkitPPC should be r28

**Comment by carstene1ns** [comment]
> recompile portlibs with latest tools.

This is currently worked on and migrated into pacman packages:
https://github.com/devkitPro/pacman-packages/tree/master/ppc
