### ISSUE TITLE
Refactor for distribution via pacman?

### ISSUE THREAD

**Issue by WinterMute** [dborth/sdl-wii#54]
Hi,

great to see you've been updating this to compile with latest tools. It would be even better if we could get it packaged and distributed via latest devkitPro pacman.

How would you feel about getting this refactored to build properly with autotools & added to https://github.com/devkitPro/pacman-packages ?

It would mean that the SDL based libraries would compile with vanilla sources too and avoid the need to supply the custom Makefiles here. There's also the convenience of supplying sdl-config in a sensible way which helps quite a bit with portability.

**Comment by sergiou87** [comment]
@WinterMute what would be the best approach for this? Just creating a wii-sdl1.2 branch from a https://github.com/devkitPro/SDL fork and submit a PR there? I might give it a try... 🤞

**Comment by sergiou87** [comment]
Probably worth closing this now that SDL for Wii is included in devkitPro https://github.com/devkitPro/pacman-packages/pull/150

😄
