### ISSUE TITLE
Problems building with latest devkitPPC?

### ISSUE THREAD

**Issue by sergiou87** [dborth/sdl-wii#57]
Not sure if I'm doing something wrong, but it builds all the object files, but when it tries to archive libSDL.a it can't find `ar` 🤯 

It's weird because it can find gcc. I tried changing the Makefile to specify the full path to `ar` and it works fine. I'm using macOS Catalina 10.15.4 (19E287) and zsh.

Logs here: [build-log.txt](https://github.com/dborth/sdl-wii/files/4767739/build-log.txt)

**Comment by TItanGuy99** [comment]
@sergiou87 I'm passing for the same issue, would you mind sharing your makefile with me? Thanks.

**Comment by sergiou87** [comment]
@TItanGuy99 Do you mean from my game? This is it: https://github.com/sergiou87/open-supaplex/blob/master/wii/Makefile

If you mean the SDL Makefile, it's not needed anymore: I helped a bit to get SDL for Wii in devkitPro so you can now install it with pacman 😄 

https://github.com/devkitPro/pacman-packages/pull/150

Let me know if you need more help.

**Comment by carstene1ns** [comment]
@TItanGuy99:
Add `-Dmain=SDL_main` to the `CFLAGS` and `-lSDLmain` after the SDL library to the `LIBS`. Reason is sdl-wii provides it's own main function that calls yours.

btw. your own portlibs additions could be simplified by adding `$(PORTLIBS)` to `LIBDIRS`

**Comment by TItanGuy99** [comment]
I got it working! Thanks a lot you two.

**Comment by vgmoose** [comment]
Is anyone seeing the following issue?
```
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/10.1.0/../../../../powerpc-eabi/bin/ld: skipping incompatible /opt/devkitpro/portlibs/wii/lib/libSDL_ttf.a when searching for -lSDL_ttf
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/10.1.0/../../../../powerpc-eabi/bin/ld: cannot find -lSDL_ttf
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/10.1.0/../../../../powerpc-eabi/bin/ld: skipping incompatible /opt/devkitpro/portlibs/wii/lib/libSDL_gfx.a when searching for -lSDL_gfx
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/10.1.0/../../../../powerpc-eabi/bin/ld: cannot find -lSDL_gfx
```

Only seeing this with SDL_ttf and SDL_gfx, image and mixer are linking ok. These are installed from dkp-pacman.

**Comment by vgmoose** [comment]
further investigation, extracting the .a files and comparing Image and ttf reveals this:

```
# file IMG.o
IMG.o: ELF 32-bit MSB relocatable, PowerPC or cisco 4500, version 1 (SYSV), with debug_info, not stripped
# file SDL_ttf.o
SDL_ttf.o: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped
```

**Comment by carstene1ns** [comment]
@vgmoose: This is a packaging issue, please file it against https://github.com/devkitPro/pacman-packages
It looks like an unclean build directory to me. If you inspect the libtool file `libSDL_ttf.la` it shows 3DS paths.

**Comment by vgmoose** [comment]
Would if I could, but I’m banned from commenting on dkP issues. All I can do is kindly request that someone else bring it up. 🥰

**Comment by carstene1ns** [comment]
Should be fixed now, @vgmoose.

**Comment by vgmoose** [comment]
can confirm! Thank you, and thanks to WinterMute as well.
