### ISSUE TITLE
Error when using the function SDL_LoadBMP

### ISSUE THREAD

**Issue by TItanGuy99** [dborth/sdl-wii#58]
Hi, I got sdl-wii compiled with the last DevKitPro but I have an issue. When I try to use the function SDL_LoadBMP I get the following error:

![file](https://user-images.githubusercontent.com/35585118/85707987-17f00680-b6ba-11ea-8c81-390662045e1d.jpg)

If I remove that I can compile my code. Do you have any work around for this? Thanks.

**Comment by carstene1ns** [comment]
This comes from linking with different newlib versions (new one used by your code and old one referenced from old sdl-wii).
Assuming you compiled sdl-wii from source, all you need to do is remove the old, incompatible library.
The installation folder has been changed, so you need to remove libSDL.a from `libogc/lib/wii` folder and the headers from `libogc/include/SDL` as well.

**Comment by TItanGuy99** [comment]
Thanks a lot! I'll check it out tonight and post the results here :)

**Comment by TItanGuy99** [comment]
Ohh I didn't know I could install it through this command: **pacman -S wii-sdl-libs**.

 One last question if you can help me (Please XD) on my files should I import like I do when I use SDL on PC? (**#include <SDL/sdl.h>**)

And on the makefile should I use the SDL flag? (**LIBS := -lSDL**)

Thanks a lot for your time.

**Comment by TItanGuy99** [comment]
I got it working, thanks a lot!
